### PR TITLE
Implement IPRBProxyStorage interface

### PR DESCRIPTION
**Pull request by andreivladbrg**
The purpose of this PR is to remove duplicated code in `PRBProxy` contract.

Changes made: 
- Added `IPRBProxyStorage` interface
- Inherit `IPRBProxyStorage` in `IPRBProxy`
- Inherit `PRBProxyStorage` in `PRBProxy`
- Moved public constant functions from `PRBProxy` to `PRBProxyStorage`
- Removed internal and public storage from `PRBProxy`

### CODE REVIEW

**Comment by PaulRBerg** [comment]
I appreciate the effort, @andreivladbrg, but unfortunately, I cannot merge this proposal.

The abstract contract `PRBProxyStorage` should not have the `getPermission` and the `getPluginForMethod` functions. It should only contain storage properties, because target contract developers may not need those getters.

**Comment by andreivladbrg** [comment]
> The abstract contract PRBProxyStorage should not have the getPermission and the getPluginForMethod functions. It should only contain storage properties, because target contract developers may not need those getters.

In that case the mappings can be set as `public`, with new version of solidity you can have named values, check this [link](https://docs.soliditylang.org/en/v0.8.19/types.html#mapping-types:~:text=In%20the%20example%20below%2C%20the%20optional%20KeyName%20and%20ValueName%20are%20provided%20for%20the%20mapping.%20It%20does%20not%20affect%20any%20contract%20functionality%20or%20bytecode%2C%20it%20only%20sets%20the%20name%20field%20for%20the%20inputs%20and%20outputs%20in%20the%20ABI%20for%20the%20mapping%E2%80%99s%20getter.).

**Comment by PaulRBerg** [comment]
As we discussed on the phone earlier, using public mappings is a fantastic idea!

The deployment cost is lowered, while the UX remains the same thanks to Solidity 0.8.18 [named mapping parameters](https://twitter.com/PaulRBerg/status/1621949932608360453)!

**Comment by PaulRBerg** [comment]
LGTM, thanks a lot, Andrei!

The Slither reports are not relevant. Will merge now.

**Review by PaulRBerg — APPROVED** [review]
LGTM, thanks a lot, Andrei!

The Slither reports are not relevant. Will merge now.

**Pull request merged**
