### PR TITLE
chore: bootstrap pnpm monorepo with mock packages

### PR DESCRIPTION
**Pull request by scorpion9979**
Addresses https://github.com/PaulRBerg/prb-proxy/issues/112
Forked from https://github.com/PaulRBerg/prb-proxy/commit/2fc7d99dc9a2debe8a014b81490d6095a67ce9d4

### CODE REVIEW

**Comment by scorpion9979** [comment]
@PaulRBerg are we looking to add a [release workflow](https://pnpm.io/workspaces#release-workflow)?

**Comment by PaulRBerg** [comment]
Thanks, @scorpion9979. Could you also work on the following tasks?

- Move the root repo into `packages/proxy` (except for the README, which I will take care of myself)
- Re-use the config files`.prettierrc.yml`, `.prettierignore` and `.solhint.json` by keeping them at the root and referencing them via `scripts` in each `package.json`
- Add the [`repository`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository) field in each `package.json`

> are we looking to add a [release workflow](https://pnpm.io/workspaces#release-workflow)?

No, not yet.

**Comment by scorpion9979** [comment]
@PaulRBerg I've added the changes discussed above. Note the file changes in .gitmodules, inspired by [Optimisim's PNPM-Foundry monorepo](https://github.com/ethereum-optimism/optimism). I've also taken liberty in setting the working-directory field in the GitHub actions to specify the current working directory to be `packages/proxy`, although I haven't yet tested it. I just added one extra commit to address the `fatal: pathspec '.gitmodules' did not match any files` error when running `forge install <dep_name>` from inside `packages/proxy` without having a local `.gitmodules` in there, but the changes has not been reflected in this PR as it was closed.

**Comment by PaulRBerg** [comment]
Thank you for the update, @scorpion9979!

I accidentally closed the PR when I deleted the `refactor/plugin-redesign ` branch - could you re-open it against `main`, please?

**Pull request closed without merging**
